### PR TITLE
Fix Kernel#inspect fails if an object doesn't have #class method

### LINKED ISSUE #2324: `Kernel#inspect` raises exception if `self.class` is undefined
Is this an intentional behavior?

```ruby
obj = Object.new
class << obj
  undef_method :class
end
print obj.inspect
```

ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
---

```
#<Object:0x00007fe84f0a8c48>%
```

truffleruby 21.1.0-dev-972a0521, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
---

```
<internal:core> core/kernel.rb:375:in `inspect': undefined method `class' for #<Object:0x18> (NoMethodError)
	from -:5:in `<main>'
```

The cause looks depending `self.class` in inspect as https://github.com/oracle/truffleruby/blob/310f0550b8cada1c89e2172182c7ab63e5014d58/src/main/ruby/truffleruby/core/kernel.rb#L375

I think it might be an intentional behavior. But I found this in testing my old tiny gem as https://github.com/kachick/validation/pull/14/checks?check_run_id=2317029150.
 
I would hope `Kernel#inspect` basically does not raise errors even if the code is not unsafe 😄

### PR DESCRIPTION
**Pull request by gogainda**
Fixes #2324

### CODE REVIEW

File: spec/ruby/language/kernel_spec.rb [hunk 1]
```diff
@@ -0,0 +1,11 @@
+require_relative '../spec_helper'
+
+describe "The Kernel class" do
+  it "inspects an object without `#class` method" do
+    obj = Object.new
+    class << obj
+      undef_method :class
+    end
+    obj.inspect.should be_kind_of(String)
+  end
```
Comment (eregon) [inline spec/ruby/language/kernel_spec.rb:10]: Could you move this spec to https://github.com/oracle/truffleruby/blob/master/spec/ruby/core/kernel/inspect_spec.rb ?

**Review by eregon — APPROVED** [review]
Thank you for the fix!
