### PR TITLE
Fix Comparable#clamp when given infinite interval

### LINKED ISSUE #3945: `#clamp` doesn't support beginless and endless Ranges
Pretty much the issue title. Trying to clamp with a beginless/endless range raises `ArgumentError`. Specifying explicit ends works, but is incovenient.

Reproduction test file:
```ruby
# frozen_string_literal: true

RSpec.describe Range do
  specify { expect { ..1 }.not_to raise_error }
  specify { expect { 1.. }.not_to raise_error }
  specify { expect { nil..nil }.not_to raise_error }

  describe "endless clamp" do
    specify { expect(13.clamp(0..12)).to eq 12 }
    specify { expect(13.clamp(0..)).to eq 13 }
    specify { expect(13.clamp(-1..)).to eq 13 }
  end

  describe "beginless clamp" do
    specify { expect(-13.clamp(-1..0)).to eq(-1) }
    specify { expect(-13.clamp(..0)).to eq(-13) }
    specify { expect(-13.clamp(..1)).to eq(-13) }
  end
end
```

Failures:
```
1) Range endless clamp 
     Failure/Error: specify { expect(13.clamp(0..)).to eq 13 }

     ArgumentError:
       min argument must be smaller than max argument
     # ./spec/range_spec.rb:10:in `block (3 levels) in <top (required)>'

  2) Range endless clamp 
     Failure/Error: specify { expect(13.clamp(-1..)).to eq 13 }

     ArgumentError:
       min argument must be smaller than max argument
     # ./spec/range_spec.rb:11:in `block (3 levels) in <top (required)>'

  3) Range beginless clamp 
     Failure/Error: specify { expect(-13.clamp(..0)).to eq(-13) }

     ArgumentError:
       min argument must be smaller than max argument
     # ./spec/range_spec.rb:16:in `block (3 levels) in <top (required)>'

  4) Range beginless clamp 
     Failure/Error: specify { expect(-13.clamp(..1)).to eq(-13) }

     ArgumentError:
       min argument must be smaller than max argument
     # ./spec/range_spec.rb:17:in `block (3 levels) in <top (required)>'
```

Tests fail on both latest versions available in `ruby/setup-ruby` action (truffleruby and truffleruby-head).

### PR DESCRIPTION
**Pull request by andrykonchin**
Changes:
- fixed Comparable#clamp called with endless/beginningless interval
- specs for range argument are taken as-is from https://github.com/ruby/spec/pull/1296 (they aren' synced yet)

Closes #3945

### CODE REVIEW

**Comment by eregon** [comment]
~The specs are sync'd now, could you rebase?~

File: src/main/ruby/truffleruby/core/comparable.rb [hunk 1]
```diff
@@ -83,10 +83,14 @@ def clamp(min, max = undefined)
     if Primitive.undefined?(max)
       range = min
       raise TypeError, "wrong argument type #{Primitive.class(range)} (expected Range)" unless Primitive.is_a?(range, Range)
-      raise ArgumentError, 'cannot clamp with an exclusive range' if range.exclude_end?
+      raise ArgumentError, 'cannot clamp with an exclusive range' if range.exclude_end? && !Primitive.nil?(range.end)
       min, max = range.begin, range.end
     end
 
+    return self if Primitive.nil?(min) && Primitive.nil?(max)
+    return self <= max ? self : max if Primitive.nil?(min)
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/comparable.rb:91]: `Primitive.min` seems tempting but probably wrong because it only handle `int` & `long`.

**Review by eregon — APPROVED** [review]
Looks good, just needs a rebase

**Comment by eregon** [comment]
> The specs are sync'd now, could you rebase?

I did it, very easy with the branch directly in this repo and not a fork :)

**Comment by andrykonchin** [comment]
Thank you!

File: spec/ruby/core/comparable/fixtures/classes.rb [hunk 2]
```diff
@@ -7,6 +7,7 @@ def initialize(value)
     end
 
     def <=>(other)
+      return nil if other.nil?
       self.value <=> other.value
     end
```
Comment (andrykonchin) [inline spec/ruby/core/comparable/fixtures/classes.rb:12]: Strictly speaking it should be

```ruby
return nil if !other.is_a?(WithOnlyCompareDefined)
```

Comment (eregon) [reply spec/ruby/core/comparable/fixtures/classes.rb:12]: True, would be more representative of real/good code
