### PR TITLE
Fix Process.spawn to raise Errno::EACCES for non-executable files

### LINKED ISSUE #4176: Wrong exception raised when attempting to run a nonexecutable file in a subprocess
Mac OS 26.3, TruffleRuby 33.0.1

```ruby
`touch hello.txt`  # succeeds
`./hello.txt`      # should error
```

This correctly raises an error, but it raises `Errno::ENOENT` with a message saying "No such file or directory". This is misleading. It probably should be either `Errno::EACCES` or `Errno::ENOEXEC`. On Mac OS, MRI 3.3.10 (and 4.0.1) raises `Errno::EACCES` with a message saying "permission denied", which I think is better.

I see similar behavior using `Process.spawn`.

### PR DESCRIPTION
**Pull request by alessandro54**
Fixes #4176

`resolve_in_path` was returning `nil` when a file was found but not executable, causing the caller to always raise `Errno::ENOENT` instead  of the correct `Errno::EACCES`.

Tested with `./hello.txt` (non-executable file) — now raises `Errno::EACCES` (Permission denied) as MRI does.

### CODE REVIEW

File: src/main/ruby/truffleruby/core/truffle/process_operations.rb [hunk 1]
```diff
@@ -630,21 +630,26 @@ def should_search_path?(command)
...
       def resolve_in_path(command)
         unless should_search_path?(command)
-          if File.file?(command) && File.executable?(command)
+          if File.file?(command)
+            raise Errno::EACCES, command unless File.executable?(command)
             return command
-          else
-            return nil
           end
+          nil
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/truffle/process_operations.rb]: Why this change?
If it shouldn't search in PATH it shouldn't use the `PATH` logic, right?

File: src/main/ruby/truffleruby/core/truffle/process_operations.rb [hunk 2]
```diff
@@ -630,21 +630,26 @@ def should_search_path?(command)
...
           file = File.join(dir, command)
-          if File.file?(file) && File.executable?(file)
-            return file
+          if File.file?(file)
+            return file if File.executable?(file)
+            found_non_executable ||= file
           end
         end
 
+        raise Errno::EACCES, found_non_executable if found_non_executable
```
[the remark this answers is not in the document]
Comment (eregon) [reply src/main/ruby/truffleruby/core/truffle/process_operations.rb]: Right, it'd be good to add a spec for this if there isn't already one in https://github.com/truffleruby/truffleruby/blob/master/spec/ruby/core/process/spawn_spec.rb

File: src/main/ruby/truffleruby/core/truffle/process_operations.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (eregon) [reply src/main/ruby/truffleruby/core/truffle/process_operations.rb]: That's a good catch. We need to set $? even if not executable:
```
$ ruby -e 'begin; spawn "./README.md"; ensure; p $?; end'
#<Process::Status: pid 31977 exit 127>
-e:1:in 'Kernel#spawn': Permission denied - ./README.md (Errno::EACCES)
	from -e:1:in '<main>'
```
Could you improve the spec in `spec/ruby/core/process/spawn_spec.rb` to check that?

We could call `resolve_in_path` before `posix_spawnp` in `spawn`, since we call it anyway.
And to be more consistent move the `raise Errno::ENOENT, "No such file or directory - #{@command}"` error there too instead of returning `nil` when not found.
We'd then need in spawn to wrap the call to `resolve_in_path` in a `rescue`, to `Primitive.thread_set_return_code Process::Status.new(-1, 127, nil, nil)` in that case, and then re-raise.
That then allows removing the entire `if not resolve_in_path(@command)` section.
The only thing we lose is not having a real PID if it fails, but I think that does not matter too much, we already don't on macOS.

There is another call to `resolve_in_path` in `exec`, that's fine and can use the new `resolve_in_path`.
`exec` does not set `$?` (makes sense, since it replaces the current process) so there no need for the `rescue`/`set $?` dance.

[the remark this answers is not in the document]
Comment (alessandro54) [reply src/main/ruby/truffleruby/core/truffle/process_operations.rb]: Thanks for the detailed feedback! I'm on it!

**Comment by alessandro54** [comment]
The CI failure is bc MRI raises Errno::ENOENT for the PATH non-executable case (confirmed on both macOS and Linux), so the spec I added diverges from MRI and can't be in `spec/ruby/`, `EACCESS` is more semantically accurate prob we can add test for TruffleRuby only.

File: src/main/ruby/truffleruby/core/truffle/process_operations.rb [hunk 3]
```diff
@@ -630,24 +621,28 @@ def should_search_path?(command)
 
       def resolve_in_path(command)
         unless should_search_path?(command)
-          if File.file?(command) && File.executable?(command)
-            return command
-          else
-            return nil
-          end
+          raise Errno::ENOENT, command unless File.file?(command)
+          raise Errno::EACCES, command unless File.executable?(command)
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/truffle/process_operations.rb]: We need better exception messages, and they should match CRuby here, not just the filename.

**Comment by eregon** [comment]
> The CI failure is bc MRI raises Errno::ENOENT for the PATH non-executable case (confirmed on both macOS and Linux), so the spec I added diverges from MRI and can't be in `spec/ruby/`, `EACCESS` is more semantically accurate prob we can add test for TruffleRuby only.

It's better to match MRI, so let's not raise any `EACCESS` for the case we are searching PATH, it also keeps the code simpler. And we can keep the other changes, they are a nice cleanup.
The spec should be changed to check it's raising ENOENT in that case.

File: src/main/ruby/truffleruby/core/truffle/process_operations.rb [hunk 4]
```diff
@@ -630,24 +621,28 @@ def should_search_path?(command)
...
+              return file if File.executable?(file)
+              found_non_executable ||= file
+            end
           end
-        end
 
-        nil
+          raise Errno::EACCES, found_non_executable if found_non_executable
+        end
+        raise Errno::ENOENT, command
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/truffle/process_operations.rb:638]: Same here (need better exception message matching CRuby)

File: src/main/ruby/truffleruby/core/truffle/process_operations.rb (hunk 3 above)
Comment (alessandro54) [reply src/main/ruby/truffleruby/core/truffle/process_operations.rb]: Could you give a concrete example of the expected message? Our raise Errno::ENOENT, command produces "No such file or directory - ./nonesuch" and raise `Errno::EACCES`, command produces "Permission denied - ./test.txt" — both match CRuby output.

**Comment by alessandro54** [comment]
@eregon   The exception messages are already matching CRuby — raise 
  Errno::ENOENT, command produces "No such file or directory - command"
   and raise Errno::EACCES, command produces "Permission denied - 
  command", both verified against MRI output. Added message assertions 
  to the specs to confirm this.

File: src/main/ruby/truffleruby/core/truffle/process_operations.rb [hunk 5]
```diff
@@ -504,24 +504,19 @@ def redirect_file_descriptor(child_fd, parent_fd, alter_process)
...
-          end
-          raise Errno::ENOENT, "No such file or directory - #{@command}"
-        elsif pid < 0
-          raise SystemCallError.new("posix_spawnp #{@command}", -pid)
+
+        # Check if the command exists before posix_spawnp to avoid zombie processes
+        # if posix_spawnp returned a pid (e.g. on Linux) but the command is not found/executable.
+        # Also sets $? like MRI does when spawn raises.
+        begin
+          resolve_in_path(@command)
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/truffle/process_operations.rb]:
```suggestion
          @command = resolve_in_path(@command)
```
Since we're doing the lookup, might as well use the result to avoid another lookup.

That also means we could switch from `posix_spawnp` to `posix_spawn` but that's a bigger change and not necessary.

File: src/main/ruby/truffleruby/core/truffle/process_operations.rb (hunk 3 above)
Comment (eregon) [reply src/main/ruby/truffleruby/core/truffle/process_operations.rb]: Ah I see, the previous code used `raise Errno::ENOENT, "No such file or directory - #{@command}"` but actually that was incorrect and produced:
```
$ ruby -e 'spawn "notexist"'
<internal:core> core/truffle/process_operations.rb:521:in 'Truffle::ProcessOperations::Execute#spawn': No such file or directory - No such file or directory - notexist (Errno::ENOENT)
```

File: spec/ruby/core/process/spawn_spec.rb [hunk 6]
```diff
@@ -694,13 +694,53 @@ def child_pids(pid)
   end
 
   it "raises an Errno::ENOENT if the command does not exist" do
-    -> { Process.spawn "nonesuch" }.should raise_error(Errno::ENOENT)
+    -> { Process.spawn "nonesuch" }.should raise_error(Errno::ENOENT, /No such file or directory.*nonesuch/)
```
Comment (eregon) [inline spec/ruby/core/process/spawn_spec.rb]: Do we need to use a Regexp here or could we assert the exact message?
The latter would be a stronger assertion and e.g. ensure we don't have `No such file or directory` twice as we used to before this PR.

Comment (alessandro54) [reply spec/ruby/core/process/spawn_spec.rb]: We can exact match, pushing the changes

Comment (eregon) [reply spec/ruby/core/process/spawn_spec.rb]: Thanks!

**Comment by eregon** [comment]
More of a self-note, there was a transient timeout in the previous CI run, unrelated to this PR:
https://github.com/truffleruby/truffleruby/actions/runs/23642478155/job/68870038412#step:7:31295
That seems the stuck test:
```
2215 2:38 /home/runner/work/truffleruby/truffleruby/test/mri/tests/lib/test/unit/parallel.rb: TestResolvDNS#test_multiple_servers_with_timeout_and_truncated_tcp_fallback
```

File: src/main/ruby/truffleruby/core/truffle/process_operations.rb (hunk 5 above)
Comment (eregon) [reply src/main/ruby/truffleruby/core/truffle/process_operations.rb]: Tracked as https://github.com/truffleruby/truffleruby/issues/4212
