### PR TITLE
Read to separator fixes

### LINKED ISSUE #2938: IO reads with a delimiter broken for multi-byte delimiters
I've been looking into test failures with Shopify's [Ruby LSP](https://github.com/Shopify/ruby-lsp) project, which is used as part of its VS Code extension. The test suite spawns a Ruby LSP server with `Open3.popen3` and sends JSON RPC messages to it from the test suite over the STDIO pipes. Sometimes the read back messages are mangled, other times they're fine.

I think I've narrowed it down to a bug in [IO::EachReader#read_to_separator](https://github.com/oracle/truffleruby/blob/7cbac4528c4bf10dbf3e84a1afaec4f1dc7c4ad0/src/main/ruby/truffleruby/core/io.rb#L1135-L1157):

```ruby
until @buffer.exhausted?
  available = @buffer.fill_from @io, @skip
  break unless available > 0

  if count = @buffer.find(@separator)
    s = @buffer.shift(count)

    unless str.empty?
      s.prepend(str)
      str.clear
    end

    s = IO.read_encode(@io, s)

    s.chomp!(@separator) if @chomp
    $. = @io.__send__(:increment_lineno)
    @buffer.discard @skip if @skip

    yield s
  else
    str << @buffer.shift
  end
end
```

The Ruby LSP test suite scans for HTTP Content-Length headers, parses the byte count from the header value, and then reads that many bytes to read in responses. In HTTP, the headers and body are separated by `\r\n\r\n`. Consequently, the test suite calls `@stdout.gets("\r\n\r\n")`. Ultimately `gets` ends up calling into the above code snippet with `@separator = "\r\n\r\n"`.

The issue is it's possible for the buffer to not have the complete pattern string. E.g., I'm seeing a case where `\r\n` appears in the first pass of the loop. That's not enough bytes to match `\r\n\r\n`, so the `else` branch is entered and those bytes are shifted out of the buffer into the response string. On the next pass through the loop the second `\r\n` now appears in the buffer, but the match fails again because the first half of the pair was removed from the buffer.

The Ruby LSP tests were giving strange results because multiple responses could be piped in and then fill the buffer such that the `\r\n\r\n` from the second response would appear in the buffer on the second pass through the loop.

In the most common cases where this code is used an explicit separator is not provided, so it defaults `$/`, which is `\n` if not overridden. With a single-byte separator we can't have a split pattern string so this code works in those cases. It looks like `IO::EachReader#read_to_separator_with_limit` has the same issue. A brief scan shows the `IO::EachReader` code is used for `IO#each`, `IO#gets` and `IO#readlines`.

/cc @vinistock

### PR DESCRIPTION
**Pull request by nirvdrum**
This PR fixes `IO::EachReader#read_to_separator` and `IO::EachReader#read_to_separator_with_limit` with multi-byte delimiters. If the delimiter appears in the IO object being read from but it split over multiple reads, the old search logic would fail to find the delimiter. Confusingly, if the delimiter appeared in full later in the IO object, that second occurrence's byte position would be returned.

I feel quite confident about the `IO::EachReader#read_to_separator` fix. This original issue was detected when working on getting the [ruby-lsp](https://github.com/Shopify/ruby-lsp) test suite passing on TruffleRuby. That test suite uses a pipe to communicate with a subprocess running the Ruby LSP server. With this PR in place those tests now pass. The new `gets` spec was based on the observed problem with that test suite. Our first attempt was insufficient because it failed to re-insert any bytes past the delimiter back into the read buffer. The test accounts for this situation.

I'm less confident about the `IO::EachReader#read_to_separator_with_limit` changes. I based them on the changes for `read_to_separator` and wrote a new `gets` spec that initially failed, but now passes. However, I don't have any real life code using this call so I can't test against that. Unfortunately, the logic is a bit more involved than simply finding the delimiter or reading the first N bytes because Ruby will read beyond N bytes to ensure only complete codepoints are returned.

Beyond that, I switched some internal calls over to primitives. And I did a minor code clean up of `IO::EachReader`. I think that code in general could benefit from a more comprehensive pass. I've left that for future work. I was aiming to keep this PR as bug fixes only. Each commit is logically standalone so we can selectively apply what's needed for now.

Fixes #2938: IO reads with a delimiter broken for multi-byte delimiters.

/cc @vinistock

### CODE REVIEW

File: spec/ruby/core/io/gets_spec.rb [hunk 1]
```diff
@@ -113,6 +113,37 @@
         $..should == @count += 1
       end
     end
+
+    describe "that consists of multiple bytes" do
+      it "should match the separator even if the buffer is filled over subsequent reads" do
+        begin
+          read, write = IO.pipe
```
Comment (eregon) [inline spec/ruby/core/io/gets_spec.rb:120]: Minor, but if `IO.pipe` would fail then we'd get a NoMethodError in the `ensure`, so it would be better to move those before the `begin`, or to use the block form of `IO.pipe` which automatically closes them at the end.

File: src/main/ruby/truffleruby/core/io.rb [hunk 2]
```diff
@@ -1143,21 +1145,84 @@ def read_to_separator
...
+            offset = found_byte_index + @separator.bytesize
+
+            # If we've read more bytes than we need to satisfy the current request, we
+            # need to put the remainder back into the buffer so that subsequent reads
+            # will have the correct bytes.
+            if offset < str.bytesize
+              @buffer.put_back(str.byteslice(offset, str.bytesize - offset))
+            end
+
+            res = IO.read_encode(@io, str[0, offset])
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/io.rb]: Does `str` always have the BINARY encoding? I think `str.byteslice(0, offset)` would be a clearer and possibly more efficient

File: src/main/ruby/truffleruby/core/io.rb [hunk 3]
```diff
@@ -1225,9 +1216,7 @@ def read_to_separator
         end
       end
 
-      str << @buffer.shift
-      str.chomp!(@separator) if @chomp
-      yield_string(str) { |y| yield y }
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/io.rb:1165]: It seems nice to replace other usages of `yield_string` too, especially since those actually cost an extra block+yield compared to `yield prepare_read_string(str) unless str.empty?`.

**Review by eregon — APPROVED** [review]
Thank you for the fix, this looks quite complicated.
@andrykonchin Could you review this PR as well, especially the bug fixes themselves, and integrate this PR?

I wonder why `s.prepend(str)` vs appending to `str` (already there before). It seems to make it much harder to reason about it.

**Comment by nirvdrum** [comment]
> Thank you for the fix, this looks quite complicated. @andrykonchin Could you review this PR as well, especially the bug fixes themselves, and integrate this PR?
> 
> I wonder why `s.prepend(str)` vs appending to `str` (already there before). It seems to make it much harder to reason about it.

We can revisit that. I remember doing that years ago to avoid string allocations in the most common case. I think this most often gets called as part of `readline` and we usually find the `\n` in the first buffer fill so it didn't make sense to read the byte array, turn that into a string (`s` in the code), that append that to an empty string (`str`), just to then yield `str`.

File: src/main/ruby/truffleruby/core/io.rb (hunk 2 above)
Comment (nirvdrum) [reply src/main/ruby/truffleruby/core/io.rb]: Good catch. It wasn't always BINARY, but I tried to change the code to always be BINARY because it's easier to reason about. I missed this case. I'll fix it.

File: src/main/ruby/truffleruby/core/io.rb (hunk 3 above)
Comment (nirvdrum) [reply src/main/ruby/truffleruby/core/io.rb:1165]: I can do that. I was just trying to keep the scope limited.

Comment (eregon) [reply src/main/ruby/truffleruby/core/io.rb:1165]: Let's do it since this usage was changed too, that way it will also avoid some duplication

**Comment by eregon** [comment]
^ ah OK, then it'd be useful if you can add a comment explaining the rationale there.

File: src/main/ruby/truffleruby/core/io.rb [hunk 4]
```diff
@@ -1242,19 +1244,40 @@ def read_to_separator_with_limit
...
-          str = +''
-          wanted = limit
+            yield s
+
+            wanted = limit
+
+            next
+          else
+            str << s
+          end
```
Comment (andrykonchin) [inline src/main/ruby/truffleruby/core/io.rb:1263]: After `str << s` we should probably adjust `wanted` as well, e.g. `wanted -= bytes_to_read` as far as `wanted = @limit - str.bytesize` is supposed to always be true.

What if `str` is longer than `@limit` now?

File: src/main/ruby/truffleruby/core/io.rb [hunk 5]
```diff
@@ -1267,13 +1290,61 @@ def read_to_separator_with_limit
...
+
+          if found_byte_index
+            offset = found_byte_index + @separator.bytesize
+
+            # If we've read more bytes than we need to satisfy the current request, we
+            # need to put the remainder back into the buffer so that subsequent reads
+            # will have the correct bytes.
+            if offset < str.bytesize
+              @buffer.put_back(str.byteslice(offset, str.bytesize - offset))
+            end
```
Comment (andrykonchin) [inline src/main/ruby/truffleruby/core/io.rb:1311]: After `@buffer.put_back` we should probably adjust `wanted` as well I suppose. I mean `wanted += str.bytesize - offset`.

**Review by andrykonchin — COMMENTED** [review]
All changes looks good 👍  (except related to `read_to_separator_with_limit`). I've left some comments.

**Comment by nirvdrum** [comment]
I looked into it and TruffleString optimizes for empty strings in an append/concat situation for either `a` or `b` in `a + b`. We had that at one point for ropes, but I think we removed it because it often made call sites polymorphic. I'm sure the Truffle team has looked at this though, so we can simplify some of that `read` implementation.

File: src/main/ruby/truffleruby/core/io.rb (hunk 5 above)
Comment (nirvdrum) [reply src/main/ruby/truffleruby/core/io.rb:1311]: I think that's right. I'll try to adjust the test to make sure we retrieve the correct number of bytes on the next read.

File: src/main/ruby/truffleruby/core/io.rb [hunk 6]
```diff
@@ -1143,21 +1145,84 @@ def read_to_separator
...
+            res.chomp!(@separator) if @chomp
+            $. = @io.__send__(:increment_lineno)
+            @buffer.discard @skip if @skip
+
+            str.clear
+            last_scan_start = 0
+
+            yield res
+          else
+            last_scan_start = str.bytesize
```
[the remark this answers is not in the document]
Comment (nirvdrum) [reply src/main/ruby/truffleruby/core/io.rb:1214]: Fair enough. I'll rename it.

File: src/main/ruby/truffleruby/core/io.rb [hunk 7]
```diff
@@ -1267,13 +1290,61 @@ def read_to_separator_with_limit
...
+
+            res = IO.read_encode(@io, str[0, offset])
+            res.chomp!(@separator) if @chomp
+            $. = @io.__send__(:increment_lineno)
+            @buffer.discard @skip if @skip
+
+            str.clear
+            last_scan_start = 0
+
+            yield res
```
[the remark this answers is not in the document]
Comment (nirvdrum) [reply src/main/ruby/truffleruby/core/io.rb:1318]: Yes. It's confusing and contrary to the documentation for `gets` with a limit value. Ruby will read enough points to complete a codepoint. That's why this method uses `@buffer.read_to_char_boundary`. I didn't change any of that logic.

[the remark this answers is not in the document]
Comment (andrykonchin) [reply src/main/ruby/truffleruby/core/io.rb:1318]: Yeah, I see. I meant that we ignore `wanted` when and return **all** bytes in `str` before the separator.

File: spec/ruby/core/io/gets_spec.rb (hunk 1 above)
Comment (nirvdrum) [reply spec/ruby/core/io/gets_spec.rb:120]: Thanks. I didn't realize there was a block form. That cleans things up.

**Comment by nirvdrum** [comment]
> I've noticed 2 more issues related to the `put_back` method:
> 
>     * we accumulate in `str` all the bytes until a separator is met so `str` might be longer (or much longer) than existing `@buffer` (in `EachReader`) that is 32kb long. `@storage.prepend(str)` increases the buffer capacity and it will never decreased until an io object is _garbage collected_. So it's kind of _memory leak_. It's probably OK but we should be aware of it and the issue may deserve to be described in a comment in the code.
>     * it seems to me that the `put_back` method is supposed to add to a buffer only just read (with `shift` method, or discarded) bytes. And it works incorrectly when we try to return back more bytes than fit in (0..`@start`) `@buffer` region. It just prepends new returned back bytes to a `@storage` and ignores `@start` index. So all the already read bytes (located in `(0...@start)` region) might be present in the buffer twice (in prepended bytes and in `@storage` itself). So I suppose `put_back` method should be adjusted as well to handle this case correctly.

Do we have any callers doing this? The only cases of `put_back` that I've used should never put back more bytes than were just read. If you're saying you think the code is doing otherwise, please let me know.

If it's just a general design note, let's start a new issue for that discussion. A lot of this code only works under specific circumstances, but it's all internal-only. A lot of it came from Rubinius and hasn't been touched much. Some of it is written weirdly to optimize because we had very IO performance in the past. Just to keep this PR focused, I'd like to keep the comments focused on things to change in this PR.

**Comment by andrykonchin** [comment]
> The only cases of put_back that I've used should never put back more bytes than were just read

Agree, my bad.
