### PR TITLE
Fix #require_relative inside an #instance_eval

### LINKED ISSUE #1079: Require semantics not the same as MRI
With https://github.com/thbar/kiba/, https://github.com/thbar/kiba-common, https://github.com/thbar/system_bang, and https://github.com/thbar/kiba-ruby-benchmarks.

```
$ ruby -I ../kiba/lib -I ../kiba-common/lib/ -I ../system_bang/lib/ ../kiba/bin/kiba csv_processing.etl 
I, [2018-02-05T21:06:16.734271 #6058]  INFO -- : Running with ruby 2.3.5
I, [2018-02-05T21:06:19.732966 #6058]  INFO -- : Processing done (took 3.0 seconds)
1406423187 519371 data/output.csv
$ jt ruby -I ../kiba/lib -I ../kiba-common/lib/ -I ../system_bang/lib/ ../kiba/bin/kiba csv_processing.etl 
$ /Users/chrisseaton/Documents/truffleruby/truffleruby/bin/truffleruby -Xcore.load_path=/Users/chrisseaton/Documents/truffleruby/truffleruby/src/main/ruby -Xgraal.warn_unless=false -I ../kiba/lib -I ../kiba-common/lib/ -I ../system_bang/lib/ ../kiba/bin/kiba csv_processing.etl
csv_processing.etl:2:in `require_relative': cannot load such file -- csv_processing.etl/etl/csv_source (LoadError)
	from csv_processing.etl:2:in `<top (required)>'
	from /Users/chrisseaton/Documents/truffleruby/kiba/lib/kiba/parser.rb:20:in `instance_eval'
	from /Users/chrisseaton/Documents/truffleruby/kiba/lib/kiba/parser.rb:20:in `parse'
	from /Users/chrisseaton/Documents/truffleruby/kiba/lib/kiba/cli.rb:12:in `run'
	from ../kiba/bin/kiba:5:in `<main>'
```

Maybe something to do with the `instance_eval`?

From https://github.com/oracle/truffleruby/issues/1054.

### PR DESCRIPTION
**Pull request by chrisseaton**
Fixes #1079.

### CODE REVIEW

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java [hunk 1]
```diff
@@ -1356,15 +1356,18 @@ private boolean callerIs(String caller) {
...
+    public abstract static class RequireRelativeNode extends CoreMethodNode {
 
-        @Specialization(guards = "isRubyString(feature)")
-        public boolean requireRelative(DynamicObject feature,
-                @Cached("create()") RequireNode requireNode) {
-            final String featureString = StringOperations.getString(feature);
-            final String featurePath = getFullPath(featureString);
+        @CreateCast("feature")
+        public RubyNode coerceToString(RubyNode feature) {
+            return NameToJavaStringNodeGen.create(feature);
```
Comment (eregon) [inline src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: NameToJavaStringNode accepts Symbol but `require_relative` does not:
```ruby
> require_relative :foo
TypeError: no implicit conversion of Symbol into String
```

But this is fine since the next commit checks with a ToPathNode fist

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java [hunk 2]
```diff
@@ -664,6 +657,32 @@ protected boolean assignsNoNewVariables(RootNodeWrapper rootNode) {
...
+            if (line == 0) {
+                // fine instead of warning because these seem common
+                Log.LOGGER.fine(() -> String.format("zero line number %s:%d not supported in #%s - will be reported as starting at 1", file, line, method));
+                return source;
+            } else if (line < 1) {
+                Log.LOGGER.warning(String.format("negative line number %s:%d not supported in #%s - will be reported as starting at 1", file, line, method));
+                return source;
+            } else if (line > 1) {
+                // fine instead of warning because we can simulate these
+                Log.LOGGER.fine(() -> String.format("offset line number %s:%d are simulated in #%s by adding blank lines", file, line, method));
```
Comment (eregon) [inline src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: Why warning here? Does it have any user-visible side effect?
If not, I think it's just our internal, but the user does not need to know about it and so we shouldn't warn.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java [hunk 3]
```diff
@@ -664,6 +657,32 @@ protected boolean assignsNoNewVariables(RootNodeWrapper rootNode) {
...
+
+                final StringBuilder builder = new StringBuilder();
+                for (int n = 1; n < line; n++) {
+                    builder.append("\n");
+                }
```
Comment (eregon) [inline src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: This seems fairly inefficient.
I know @nirvdrum optimized this, so please use the code below:
```java
            final char[] emptyLines = new char[Math.max(line - 1, 0)];
            Arrays.fill(emptyLines, '\n');
            Source source = Source.newBuilder(new String(emptyLines) + code)
```

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java [hunk 4]
```diff
@@ -664,6 +657,32 @@ protected boolean assignsNoNewVariables(RootNodeWrapper rootNode) {
         private boolean frameHasOnlySelf(final FrameDescriptor descriptor) {
             return descriptor.getSize() == 1 && SelfNode.SELF_IDENTIFIER.equals(descriptor.getSlots().get(0).getIdentifier());
         }
+
+        @TruffleBoundary
+        public static String offsetSource(String method, String source, String file, int line) {
```
Comment (eregon) [inline src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: Looks to me like this should return a Source, any reason not to?

File: spec/ruby/core/kernel/require_relative_spec.rb [hunk 5]
```diff
@@ -40,6 +40,18 @@
     ScratchPad.recorded.should == [:loaded]
   end
 
+  it "loads a path relative to a file base name as specified in an #instance_eval" do
+    Dir.chdir File.dirname(File.join(__dir__, @path)) do
```
Comment (eregon) [inline spec/ruby/core/kernel/require_relative_spec.rb]: Can you use `Dir.chdir @abs_dir` here, since it's already computed above and easier to read?

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java [hunk 6]
```diff
@@ -1421,7 +1421,7 @@ private String getFullPath(final String featureString) {
         private String dirname(String path) {
             final int lastSlash = path.lastIndexOf(File.separatorChar);
             if (lastSlash == -1) {
-                return path;
+                return getContext().send(getContext().getCoreLibrary().getDirClass(), "getwd").toString();
```
Comment (eregon) [inline src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: Use `FeatureLoader.getWorkingDirectory()` (needs to be made public)

Comment (eregon) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: What if the passed path contains a `/` but is still relative (like `a/b`)?
I think it should still be interpreted relative to CWD in such a case.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java (hunk 2 above)
Comment (chrisseaton) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: It'll show up in things like tooling, where you may get screens of empty text. I could also write a `TODO` comment so we remember something weird is going on but I'm trying to move away from doing that as we start to think about releases, so that weird things show up in users' logs and we can find them.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java (hunk 3 above)
Comment (chrisseaton) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: Ok.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java (hunk 4 above)
Comment (chrisseaton) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: I try to make each method know about as few classes as possible to reduce complexity. The caller of this method needs to create a `Source`, but this method can be simpler and only deal with the strings, not knowing anything about sources.

File: spec/ruby/core/kernel/require_relative_spec.rb (hunk 5 above)
Comment (chrisseaton) [reply spec/ruby/core/kernel/require_relative_spec.rb]: Ok.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java (hunk 6 above)
Comment (chrisseaton) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: I'll add a spec and find out what happens.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java (hunk 2 above)
Comment (eregon) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: I see, makes sense.
Maybe we should have different levels to differentiate higher-level initialization messages (like initalizeContext()).

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java (hunk 4 above)
Comment (eregon) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: But then each caller duplicates the creation of a Source, and this method seems to already have all the information needed to create a Source, so I think it's better to create the Source here.
Furthermore, maybe we could have an abstraction on top of Source to deal with these weird line numbers, or at some point integrate such a change in Source itself, and then it would still make sense to keep this method to deal with negative line numbers, etc.
It could be 2 different methods (one private for String processing and one building the Source from the information), of course.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java (hunk 2 above)
Comment (chrisseaton) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: Different logging levels? This is already `fine` so it doesn't show up by default.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java (hunk 4 above)
Comment (chrisseaton) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: > so I think it's better to create the Source here

Well I'll create another help method to create the `Source` that they can all use then.

> Furthermore, maybe we could have an abstraction on top of Source to deal with these weird line numbers, or at some point integrate such a change in Source itself

Yes there's an issue open for offset line numbers, including negative, GR-9504. I don't want to add our own abstraction around source if we can avoid it, and I don't want to add it temporarily.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java [hunk 7]
```diff
@@ -1426,11 +1426,16 @@ private String getFullPath(final String featureString) {
         }
 
         private String dirname(String path) {
-            final int lastSlash = path.lastIndexOf(File.separatorChar);
-            if (lastSlash == -1) {
-                return getContext().getFeatureLoader().getWorkingDirectory();
+            if (path.charAt(0) == File.separatorChar) {
+                return path.substring(0, path.lastIndexOf(File.separatorChar));
```
Comment (eregon) [inline src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: What happens if `path` is just `"/"`?

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java [hunk 8]
```diff
@@ -1426,11 +1426,16 @@ private String getFullPath(final String featureString) {
...
             } else {
-                return path.substring(0, lastSlash);
+                final String workingDirectory = getContext().getFeatureLoader().getWorkingDirectory();
+                final int lastIndex = path.lastIndexOf(File.separatorChar);
+                if (lastIndex == -1) {
+                    return workingDirectory;
+                } else {
+                    return workingDirectory + "/" + path.substring(0, path.lastIndexOf(File.separatorChar));
```
Comment (eregon) [inline src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: `path.lastIndexOf(File.separatorChar)` could be replaced by `lastIndex`, which would make it easier to read.

Comment (chrisseaton) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: Fixing.

File: src/main/java/org/truffleruby/core/kernel/KernelNodes.java (hunk 7 above)
Comment (chrisseaton) [reply src/main/java/org/truffleruby/core/kernel/KernelNodes.java]: Works; spec added.
