### PR TITLE
Fix wrong constant/identifier detection in lexer for non-ascii encodings

### LINKED ISSUE #2079: Dynamic constant assignment using non-ascii variable
From one of our libraries we have this:
```
def variance
  μ = mean
  reduce(0) { |m, i| m + (i - μ).square } / (length - 1)
end
```

In TruffleRuby, this results in: `SyntaxError: dynamic constant assignment`

### PR DESCRIPTION
**Pull request by ivoanjo**
During lexing/parsing, a token is determined to be an identifier or a constant by looking at its first byte and determining if it is an uppercase character: Constants start with an uppercase character, identifiers start with a lowercase one.

But as previously implemented, only the first byte of a token was used when checking if a character is an upper or lowercase one, which breaks under multibyte encodings, such as UTF-8.

For instance, in #2079 a user reported that

```ruby
def variance
  μ = mean
  reduce(0) { |m, i| m + (i - μ).square } / (length - 1)
end
```

caused a `SyntaxError: dynamic constant assignment` because `μ` ([Greek Small Letter Mu](https://www.compart.com/en/unicode/U+03BC)) is encoded with UTF-8 as (206, 188), and `Character.isUpperCase(206) == true`. Thus, the code was considering it a constant, even though the character is considered a lowercase letter by the unicode standard (and thus by MRI).

Interestingly enough, the reverse can happen.

```ruby
def foo
  Ⴀ = 1
end
```

The character `Ⴀ` ([Georgian Capital Letter An](https://www.compart.com/en/unicode/U+10A0)) is encoded with UTF-8 as (225, 130, 160) and `isUpperCase(225) == false` making TruffleRuby accept it as an identifier in the example, where MRI rejects it with `SyntaxError: dynamic constant assignment` because it considers it to be a constant.

The fix is thus to extract the entire character on multi-byte encodings, and thus the `isUpperCase` check becomes correct.

To discuss before merging:

* This extracts the first character in a rather heavy-handed way -- it converts the entire `Rope` representation of the token into a `String` instance, and then extracts the `String`'s first character.

  This is definitely correct but it's a rather expensive conversion just to grab the first character -- especially given that most of the time Ruby sources are only the ASCII subset of UTF-8 and thus are not using multibyte characters.

  I was digging through the `Rope` implementation and could not find a nice way of getting only a single character that can be used by the lexer/parser. One low-hanging improvement is to add a fast path for   ASCII/UTF-8 single-byte characters, and in other cases fall back to the heaver approach. Thoughts?

* What's the best way to add a regression test for this? I was looking through the codebase and there doesn't seem to be a a lot of TruffleRuby-specific tests, but I'm not sure if this would fit within ruby/spec.

fixes #2079

### CODE REVIEW

**Comment by eregon** [comment]
> What's the best way to add a regression test for this? I was looking through the codebase and there doesn't seem to be a a lot of TruffleRuby-specific tests, but I'm not sure if this would fit within ruby/spec.

This is definitely a good case for a language spec in ruby/spec (so just edit files under `spec/ruby` in this repo).
It's on purpose there are few  TruffleRuby-specific tests, so we share tests/specs as much as we can with other Ruby implementations.

File: src/main/java/org/truffleruby/parser/lexer/RubyLexer.java [hunk 1]
```diff
@@ -1798,7 +1798,7 @@ private int identifier(int c, boolean commandState) {
             }
             tempVal = createTokenRope();
 
-            if (result == 0 && Character.isUpperCase(tempVal.get(0) & 0xFF)) {
+            if (result == 0 && Character.isUpperCase(tempVal.getString().charAt(0))) {
```
Comment (eregon) [inline src/main/java/org/truffleruby/parser/lexer/RubyLexer.java:1801]: `charAt()` might not work if the character would be a surrogate and need 2 `char` to be represented.
`codePointAt(0)` is a possible fix for that.

I think it is possible to query directly via JCodings without converting to java.lang.String by using `Encoding#mbcToCode` and `Encoding#isUpper` (seems worth a helper method). That should be more efficient.

File: src/main/java/org/truffleruby/parser/lexer/RubyLexer.java [hunk 2]
```diff
@@ -3493,12 +3493,12 @@ public boolean update_heredoc_indent(int c) {
...
 
     public void validateFormalIdentifier(Rope identifier) {
-        int first = identifier.get(0) & 0xFF;
-
-        if (Character.isUpperCase(first)) {
+        if (isFirstCharacterEncodingAwareUppercase(identifier)) {
             compile_error("formal argument cannot be a constant");
         }
 
+        int first = identifier.getString().charAt(0);
```
Comment (eregon) [inline src/main/java/org/truffleruby/parser/lexer/RubyLexer.java:3500]: We should still use `int first = identifier.get(0) & 0xFF;` here to avoid creating an intermediate Java String.

**Review by eregon — COMMENTED** [review]
This looks great, thanks!
The OCA is required before merging though.

File: src/main/java/org/truffleruby/parser/lexer/RubyLexer.java [hunk 3]
```diff
@@ -3665,4 +3665,11 @@ protected boolean isSpaceArg(int c, boolean spaceSeen) {
         return isARG() && spaceSeen && !Character.isWhitespace(c);
     }
 
+    /** Encoding-aware (including multi-byte encodings) check of first character of a given rope, usually to determine
+     * if it is a constant */
+    private boolean isFirstCharacterEncodingAwareUppercase(Rope rope) {
+        byte[] ropeBytes = rope.getBytes();
+        int firstCharacter = rope.encoding.mbcToCode(ropeBytes, 0, ropeBytes.length);
+        return rope.encoding.isUpper(firstCharacter);
+    }
```
Comment (nirvdrum) [inline src/main/java/org/truffleruby/parser/lexer/RubyLexer.java:3674]: I'd be curious to see if short-circuiting for ASCII would be beneficial. Something like:

```java
int firstByte = rope.get(0) & 0xFF;
if (rope.encoding.isAsciiCompatible() && isASCII(firstByte)) {
    return StringSupport.isAsciiUppercase(firstByte);
} else {
    final byte[] ropeBytes = rope.getBytes();
    final int firstCodepoint = rope.encoding.mbcToCode(ropeBytes, 0, ropeBytes.length);

    return rope.getEncoding().isUpper(firstCodepoint);
}
```

Depending on the structure of the rope, not having to materialize the whole thing may be advantageous.

It'd be really nice if you could use `RopeNodes.GetCodePointNode` here. But it's probably more expensive than what you're doing here.

File: src/main/java/org/truffleruby/parser/lexer/RubyLexer.java [hunk 4]
```diff
@@ -3665,4 +3665,11 @@ protected boolean isSpaceArg(int c, boolean spaceSeen) {
         return isARG() && spaceSeen && !Character.isWhitespace(c);
     }
 
+    /** Encoding-aware (including multi-byte encodings) check of first character of a given rope, usually to determine
+     * if it is a constant */
+    private boolean isFirstCharacterEncodingAwareUppercase(Rope rope) {
+        byte[] ropeBytes = rope.getBytes();
+        int firstCharacter = rope.encoding.mbcToCode(ropeBytes, 0, ropeBytes.length);
```
Comment (nirvdrum) [inline src/main/java/org/truffleruby/parser/lexer/RubyLexer.java:3672]: Minor thing, but I think this is more accurately the first codepoint.

File: src/main/java/org/truffleruby/parser/lexer/RubyLexer.java (hunk 3 above)
Comment (eregon) [reply src/main/java/org/truffleruby/parser/lexer/RubyLexer.java:3674]: Regarding the ASCII case, it would be interesting to see if it makes a difference that can be seen in parse time.

Regarding `GetCodePointNode` it would be possible by making it `@GenerateUncached` (not very hard, but seems out of scope of this PR).
I would think most (all?) Ropes in the lexer/parser are SubstringRope.
It could be interesting to have a specialization (or new Rope#getBytesWithOffset(), Rope#getByteOffset() methods) in `GetCodePointNode` to be able to reuse the parent Rope's bytes (+ offset and length) and avoid an extra copy. Although since this is about identifiers they are likely rather short and the copy is likely therefore not expensive.
In the future, maybe TruffleString can support an optimized `getFirstCodePoint()` or so.

Comment (ivoanjo) [reply src/main/java/org/truffleruby/parser/lexer/RubyLexer.java:3674]: The ASCII short-circuit seems simple enough, and indeed it'll probably be the most common codepath. I'll update the PR with it.

As for measuring, any suggestions on how to best isolate the parsing?

**Comment by ivoanjo** [comment]
> This looks great, thanks!
> The OCA is required before merging though.

Yeap, I'll have it ready ASAP :)

File: src/main/java/org/truffleruby/parser/lexer/RubyLexer.java (hunk 3 above)
Comment (eregon) [reply src/main/java/org/truffleruby/parser/lexer/RubyLexer.java:3674]: You can use this to measure parse time (either total or per file):
https://github.com/oracle/truffleruby/blob/master/doc/contributor/profiling.md#require-profiling

It's likely much better to run this in the native configuration (`jt build --env native` and then `jt -u native ruby ...`), otherwise it will include some classloading, etc.

Comment (ivoanjo) [reply src/main/java/org/truffleruby/parser/lexer/RubyLexer.java:3681]: I've did a few simple tests and the numbers were too close to the margin of error to tell:
    
* `master` (without the fix to #2079): avg 57.7ms, median 57ms, p90 64ms
* with fast path: avg 57.8ms, median 58ms, p90 63ms
* without fast path (previous commit): avg 56.7ms, median 56ms, p90 63ms

Since the fast path is very simple and local to the method, I suggest keeping it anyway.

**Comment by ivoanjo** [comment]
Update on the OCA: I sent the signed document in last Thursday but haven't yet heard back. Hopefully some will be able to process it soon.

**Review by eregon — APPROVED** [review]

**Comment by eregon** [comment]
@ivoanjo This finally got merged, thanks for the fix!

Apologies for the delay, there was also some mixup with the OCA, which meant it took longer to process it.

**Comment by ivoanjo** [comment]
As they say on Kill Bill: "Hard part's over" ;)

It's the first, but definitely there will be more. Thanks for the review!
