### PR TITLE
Fix Rational() arguments type conversion and add :exception keyword argument

### LINKED ISSUE #3969: `Kernel#Rational` behaves differently from MRI when `#to_r` raises error
When a class implementes `#to_r`, `Kernel#Rational` calls it. However, if this call raises an error, MRI just lets the error through, while TruffleRuby changes it to `TypeError`. Other methods, like `#Integer` and `#Float`, pass error through.

Additionally, `exception:` keyword argument doesn't seem to be supported at all?

Reproduction spec:
```rb
# frozen_string_literal: true

RSpec.describe "Kernel#Rational" do
  subject(:result) { Rational(A.new(value)) }

  a =
    Class.new do
      def initialize(value)
        @value = value
      end

      def to_r
        @value.zero? ? @value : raise(ZeroDivisionError)
      end
    end

  before { stub_const("A", a) }

  context "when #to_r works" do
    let(:value) { 0r }

    it "returns the value" do
      expect(result).to be value
    end
  end

  context "when #to_r fails" do
    let(:value) { 1.0 }

    it "raises ZeroDivisionError" do
      expect { result }.to raise_error ZeroDivisionError
    end

    context "with exception: false" do
      subject(:result) { Rational(A.new(value), exception: false) }

      it "returns nil" do
        expect(result).to be nil
      end
    end
  end
end
```

On TruffleRuby this produces:
```
Failures:

  1) Kernel#Rational when #to_r fails raises ZeroDivisionError
     Failure/Error: expect { result }.to raise_error ZeroDivisionError

       expected ZeroDivisionError, got #<TypeError: wrong argument type A (expected Rational)> with backtrace:
         # ./spec/truffle_spec.rb:4:in `result'
         # ./spec/truffle_spec.rb:31:in `block (4 levels) in <top (required)>'
         # ./spec/truffle_spec.rb:31:in `block (3 levels) in <top (required)>'
     # ./spec/truffle_spec.rb:31:in `block (3 levels) in <top (required)>'

  2) Kernel#Rational when #to_r fails with exception: false returns nil
     Failure/Error: subject(:result) { Rational(A.new(value), exception: false) }

     TypeError:
       numerator is not an Integer
     # ./spec/truffle_spec.rb:35:in `result'
     # ./spec/truffle_spec.rb:38:in `block (4 levels) in <top (required)>'
```

This is probably connected to #3954, as both issues point to `#Rational` behaving quite differently compared to MRI.

### PR DESCRIPTION
**Pull request by andrykonchin**
Closes #3969, #3954

### CODE REVIEW

File: src/main/ruby/truffleruby/core/rational.rb [hunk 1]
```diff
@@ -342,25 +346,94 @@ def self.convert(num, den)
     when Integer
       # nothing
     when String
-      num = String::Rationalizer.new(num).strict_convert
+      if exception
+        num = String::Rationalizer.new(num).strict_convert
+      else
+        num = String::Rationalizer.new(num).convert(nil)
+        return nil if Primitive.nil?(num)
+      end
```
Comment (andrykonchin) [inline src/main/ruby/truffleruby/core/rational.rb:354]: `convert(nil)` seems to me slightly better than `internal_convert()` that looks like a "not-public" method.

File: src/main/ruby/truffleruby/core/rational.rb [hunk 2]
```diff
@@ -342,25 +346,94 @@ def self.convert(num, den)
...
     when Float, Complex
       num = num.to_r
+    else
+      if !num.respond_to?(:to_r)
+        begin
+          integer = Truffle::Type.rb_check_to_integer(num, :to_int)
+          num = integer if integer
+        rescue Exception
+        end
+      end
```
Comment (andrykonchin) [inline src/main/ruby/truffleruby/core/rational.rb:365]: `rescue Exception` is imitating `rb_protected`. Wondering if there is a better way.

Comment (eregon) [reply src/main/ruby/truffleruby/core/rational.rb:365]: Would `rb_check_funcall` work here?
I think suppressing exceptions is always a mistake, so I think we should not do it, even if CRuby does it.

File: src/main/ruby/truffleruby/core/rational.rb [hunk 3]
```diff
@@ -345,22 +345,49 @@ def self.convert(num, den)
...
+    else
+      if !Primitive.respond_to?(den, :to_r, false)
+        integer = Truffle::Type.rb_check_to_integer(den, :to_int)
+        den = integer if integer
+      end
+    end
+
+    if Primitive.is_a?(num, Rational) && Primitive.equal?(den, 1)
+      return num
     end
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/rational.rb]: This seems a weird shortcut semantically, I would omit if not necessary (seem not necessary, the next `if` will handle it fine)

File: src/main/ruby/truffleruby/core/rational.rb [hunk 4]
```diff
@@ -345,22 +345,49 @@ def self.convert(num, den)
...
+
+      if Primitive.is_a?(num, Numeric) && Primitive.is_a?(den, Numeric) &&
+          !(Primitive.is_a?(num, Integer) && Primitive.is_a?(den, Integer))
+        rational = Truffle::Type.rb_check_convert_type(num, Rational, :to_r)
+        num = rational if rational
+        return num / den
+      end
     end
 
+    # num and dun are supposed to be Rational or Integer here
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/rational.rb]: `# num and den`

File: src/main/ruby/truffleruby/core/rational.rb [hunk 5]
```diff
@@ -345,22 +345,49 @@ def self.convert(num, den)
...
+    if Primitive.is_a?(num, Rational) && Primitive.equal?(den, 1)
+      return num
     end
 
-    if Primitive.equal?(den, 1) && !(Primitive.is_a?(num, Integer))
-      return Truffle::Type.coerce_to(num, Rational, :to_r)
-    elsif Primitive.is_a?(num, Numeric) && Primitive.is_a?(den, Numeric) &&
-        !(Primitive.is_a?(num, Integer) && Primitive.is_a?(den, Integer))
-      return num / den
+    if !Primitive.is_a?(num, Integer) && Primitive.equal?(den, 1) # that's den either isn't given or equals 1
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/rational.rb]: `# den isn't given or is 1`

File: src/main/ruby/truffleruby/core/rational.rb (hunk 2 above)
Comment (eregon) [reply src/main/ruby/truffleruby/core/rational.rb:365]: Ah there is `exception: true/false`, then can we `return nil` in this `rescue Exception`?

File: src/main/ruby/truffleruby/core/rational.rb (hunk 1 above)
Comment (eregon) [reply src/main/ruby/truffleruby/core/rational.rb:354]: Right, the whole class is private but encapsulation-wise it makes sense to make `internal_convert` `private` to clarify that

File: src/main/ruby/truffleruby/core/rational.rb (hunk 2 above)
Comment (eregon) [reply src/main/ruby/truffleruby/core/rational.rb:365]: Also this needs to reraise if `exception` is `true`, isn't it?

File: src/main/ruby/truffleruby/core/rational.rb [hunk 6]
```diff
@@ -342,25 +346,43 @@ def self.convert(num, den)
...
       den = den.to_r
     else
       if !Primitive.respond_to?(den, :to_r, false)
-        integer = Truffle::Type.rb_check_to_integer(den, :to_int)
-        den = integer if integer
+        begin
+          integer = Truffle::Type.rb_check_to_integer(den, :to_int)
+          den = integer if integer
+        rescue Exception # rubocop:disable Lint/RescueException, Lint/SuppressedException
+        end
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/rational.rb]: Same here, should reraise if exception, and return nil otherwise

File: src/main/ruby/truffleruby/core/rational.rb [hunk 7]
```diff
@@ -369,14 +391,38 @@ def self.convert(num, den)
...
-      return Truffle::Type.rb_convert_type(num, Rational, :to_r)
+      if exception
+        return Truffle::Type.rb_convert_type(num, Rational, :to_r)
+      else
+        begin
+          return Truffle::Type.rb_convert_type(num, Rational, :to_r)
+        rescue Exception # rubocop:disable Lint/RescueException
+          return nil
+        end
+      end
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/rational.rb]: Can you avoid the duplication by always have the rescue, and simply reraise `if exception`? Same below

File: src/main/ruby/truffleruby/core/rational.rb [hunk 8]
```diff
@@ -342,6 +342,10 @@ def self.convert(num, den, exception)
       return reduce(num, den)
     end
 
+    if Primitive.is_a?(num, Complex) && num.imag == 0
+      num = num.real
+    end
```
Comment (eregon) [inline src/main/ruby/truffleruby/core/rational.rb]: Is this condition needed?
I think it should work fine via `to_r` coercion (or `to_int`) as already done below

**Comment by eregon** [comment]
Sorry for the late review, I missed this PR somehow

File: src/main/ruby/truffleruby/core/rational.rb (hunk 8 above)
Comment (andrykonchin) [reply src/main/ruby/truffleruby/core/rational.rb]: ~~Yeah, `Complex#to_r` doesn't work if the imaginary component is present:~~

Ah, right. It's completely equivalent `Complex#to_r` followed by `Rational#to_i`.

```ruby
Complex(1, 2).to_r
# (irb):2:in `to_r': can't convert 1+2i into Rational (RangeError)

Complex(1, 0).to_r
# => (1/1)
```

File: src/main/ruby/truffleruby/core/rational.rb (hunk 2 above)
Comment (andrykonchin) [reply src/main/ruby/truffleruby/core/rational.rb:365]: Actually it's handled bellow by converting to Rational and calling `#to_r`. As far as an argument doesn't respond to `#to_r` - the method will either return `nil` or raise an exception.

But returning `nil` immediately is kind of performance optimisation. Will add it. Exception is not re-raised. `TypeError` raised instead (a bit further probably).

**Comment by andrykonchin** [comment]
Rebased on master because of conflicts in the changelog.

**Comment by eregon** [comment]
Mmh looks like I broke master :sweat: 
https://github.com/truffleruby/truffleruby/actions/runs/20282055071/job/58246426732?pr=4045

**Comment by eregon** [comment]
Fixed in https://github.com/truffleruby/truffleruby/pull/4060
